[package]
name = "assistant"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.5.1" }
candle-nn = { git = "https://github.com/huggingface/candle.git", version = "0.5.1" }
cpal = "0.15.3"
crossbeam-channel = "0.5.13"
crossterm = "0.27.0"
js-sandbox = "0.1.6"
rand = "0.8.5"
ratatui = { version = "0.26.3", features = ["all-widgets"] }

[features]
cuda = ["candle-core/cuda", "candle-nn/cuda"]
