[package]
name = "assistant"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.5.1" }
candle-nn = { git = "https://github.com/huggingface/candle.git", version = "0.5.1" }
cpal = "0.15.3"
crossbeam-channel = "0.5.13"
crossterm = "0.27.0"
deno_core = "0.283.0"
rand = "0.8.5"
ratatui = { version = "0.26.3", features = ["all-widgets"] }
reqwest = "0.12.4"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
serde_v8 = "0.192.0"
tokio = { version = "1.37.0", features = ["full"] }

[features]
cuda = ["candle-core/cuda", "candle-nn/cuda"]
